apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-replicas
  annotations:
    policies.kyverno.io/description: >-
      This policy checks for replicas greater than or equal to 3
spec:
  rules:
    - name: check-replicas
      match:
        all:
        - (steps[?newState.type=='kubernetes:apps/v1:Deployment'] | length(@) > `0` ): true
      assert:
        all:
        - message: Replicas should be greater or equal to 3
          check:
            ~.(steps[?newState.type=='kubernetes:apps/v1:Deployment']):
              newState:
                inputs:
                  spec:
                    (replicas >= `3`): true
