apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: enable-secrets-encryption
  annotations:
    policies.kyverno.io/title: Enable Secrets Encryption
    policies.kyverno.io/category: CIS EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Enabling secrets encryption for EKS cluster minimizes the risk of unauthorized access and potential security breaches by reducing the attack surface of the EKS control plane. 
  labels:
    app: cloud-control-point
spec:
  validationActions:
    - Deny
  evaluation:
    mode: JSON
    background:
      enabled: false
  matchConstraints:
    resourceRules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
        operations: ["CREATE", "UPDATE"]
  matchConditions:
    - name: is-terraform-plan
      expression: "has(object.planned_values) && has(object.terraform_version)"
    - name: has-eks-cluster
      expression: |
        has(object.planned_values) && 
          (has(object.planned_values.root_module) && has(object.planned_values.root_module.child_modules) &&
           object.planned_values.root_module.child_modules.exists(m, 
             has(m.resources) && m.resources.exists(r, r.type == 'aws_eks_cluster')))
  validations:
    - expression: |
          (!has(object.planned_values.root_module.child_modules) ||
           object.planned_values.root_module.child_modules.all(module,
             !has(module.resources) ||
             module.resources.filter(r, r.type == 'aws_eks_cluster').all(cluster,
               !has(cluster.values.encryption_config) ||
               cluster.values.encryption_config.all(encryption_config,
                 !has(encryption_config.resources) || encryption_config.resources.exists(resource, resource == 'secrets')
               )
             )
           ))
      message: "Secrets encryption is enabled. The field cluster.encryptionConfig is defined for secrets."
